# Generated by Django 5.0.4 on 2024-06-14 17:50

import categories.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0002_alter_menu_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('icon', models.ImageField(blank=True, upload_to=categories.models.category_icon_upload_to, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='menus.menu')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='categories__name_e3ad98_idx')],
            },
        ),
    ]
