# Generated by Django 5.0.4 on 2024-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('menus', '0003_menu_menus_menu_owner_i_6c7575_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['menu', 'is_active'], name='categories__menu_id_e0f1a8_idx'),
        ),
    ]
