# Generated by Django 5.0.4 on 2024-06-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='address',
            field=models.TextField(blank=True, max_length=255, verbose_name='address'),
        ),
    ]
