# Generated by Django 5.0.4 on 2024-06-15 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['owner', 'is_active'], name='menus_menu_owner_i_6c7575_idx'),
        ),
    ]
