# Generated by Django 5.0.4 on 2024-06-12 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='menu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='menu_menu_name_4933c0_idx'), models.Index(fields=['slug'], name='menu_menu_slug_ba1143_idx')],
            },
        ),
    ]
